### ISSUE TITLE
Bug: Background Image is getting repeated in screens having height greater than 740 pixels

### ISSUE THREAD

**Issue by adit19shah** [flyingsonu122/Diwali-Wishes#2]
I'm submitting a 
- [x] bug report
- [ ] feature request

**Current behavior:**
 Background image is getting vertically repeated in screens having height greater than 740 pixels

![image](https://user-images.githubusercontent.com/58650668/96358065-bc420100-1120-11eb-8f7a-b05b13028fbe.png)

**Expected behavior:**
Background image should not get vertically repeated and it should spread entirely in the area available as a whole

**Comment by adit19shah** [comment]
@flyingsonu122 Can you please add Hacktoberfest label to it ? so that my PR gets counted towards the Hacktoberfest 2020.

**Comment by iamsonukushwaha** [comment]
Sure

**Comment by adit19shah** [comment]
Thank You !
